###
POST http://localhost:4000/register HTTP/1.1
Content-Type: application/json

{
    "username": "Juan",
    "password": "123",
    "age": 59,
    "repeatPassword": "123",
    "email": "juan4@dev.com"
}

###
GET http://localhost:4000 HTTP/1.1
